#!/bin/bash

stagedFiles=$(git diff --staged --name-only)

echo "Formatting files"
./gradlew spotlessApply

if [ $? -eq 0 ]; then
    echo "Formatting files succeeded"
    for file in $stagedFiles; do
        if test -f "$file"; then
            git add $file
        fi
    done
else
    echo "Formatting files failed" >&2
    exit 1
fi