name: Build

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary-as-pr-comment: on-failure

      - name: Build with Gradle
        run: ./gradlew build